### ISSUE TITLE
Maybe try Coalton?

### ISSUE THREAD

**Issue by stylewarning** [jjensenral/AdventOfCode2021#1]
I don't actually have an issue with your personal project, but I noticed that you wanted to try writing AoC in a stricter functional style. 😄 

If you haven't heard of it, [Coalton](https://coalton-lang.github.io/20211010-introducing-coalton/) is an embedded, statically type-checked DSL in Common Lisp. [I solved the first AoC problem](https://github.com/stylewarning/aoc/blob/main/2021/1/1.lisp) in it, as have a few others. It's interoperable with Lisp, and allows you to write programs partially or wholly in Coalton.

There's even a little [contest](https://coalton-lang.github.io/20211129-aoc-contest/) going on, if you're interested.

Cheers, and happy hacking!

**Comment by jjensenral** [comment]
Many thanks for the suggestion @stylewarning ! I will definitely try it out.
